apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-frontend
  namespace: ems-app
  labels:
    app: ems-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ems-frontend
  template:
    metadata:
      labels:
        app: ems-frontend
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: frontend
          image: frontend-image
          imagePullPolicy: Always
          env:
            - name: API_BASE_URL
              value: "http://ems-backend.ems-app.svc.cluster.local:8080/api"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
